-- Auto-populate empty domain values for CompTIA exam questions
-- Generated from each question's explanation text.
USE comptia_exam_db;

UPDATE questions SET domain = 'Visualization and reporting' WHERE q_num = 1;
UPDATE questions SET domain = 'Data acquisition and preparation' WHERE q_num = 2;
UPDATE questions SET domain = 'Data concepts and environments' WHERE q_num = 3;
UPDATE questions SET domain = 'Data governance' WHERE q_num = 4;
UPDATE questions SET domain = 'Visualization and reporting' WHERE q_num = 5;
UPDATE questions SET domain = 'Visualization and reporting' WHERE q_num = 6;
UPDATE questions SET domain = 'Data acquisition and preparation' WHERE q_num = 7;
UPDATE questions SET domain = 'Visualization and reporting' WHERE q_num = 8;
UPDATE questions SET domain = 'Data concepts and environments' WHERE q_num = 9;
UPDATE questions SET domain = 'Visualization and reporting' WHERE q_num = 10;
UPDATE questions SET domain = 'Data analysis' WHERE q_num = 11;
UPDATE questions SET domain = 'Data governance' WHERE q_num = 12;
UPDATE questions SET domain = 'Data governance' WHERE q_num = 13;
UPDATE questions SET domain = 'Data acquisition and preparation' WHERE q_num = 14;
UPDATE questions SET domain = 'Data analysis' WHERE q_num = 15;
UPDATE questions SET domain = 'Data governance' WHERE q_num = 16;
UPDATE questions SET domain = 'Data concepts and environments' WHERE q_num = 17;
UPDATE questions SET domain = 'Data acquisition and preparation' WHERE q_num = 18;
UPDATE questions SET domain = 'Data concepts and environments' WHERE q_num = 19;
UPDATE questions SET domain = 'Data governance' WHERE q_num = 21;
UPDATE questions SET domain = 'Data governance' WHERE q_num = 22;
UPDATE questions SET domain = 'Data analysis' WHERE q_num = 23;
UPDATE questions SET domain = 'Visualization and reporting' WHERE q_num = 24;
UPDATE questions SET domain = 'Data concepts and environments' WHERE q_num = 25;
UPDATE questions SET domain = 'Data analysis' WHERE q_num = 26;
UPDATE questions SET domain = 'Visualization and reporting' WHERE q_num = 27;
UPDATE questions SET domain = 'Data analysis' WHERE q_num = 28;
UPDATE questions SET domain = 'Data concepts and environments' WHERE q_num = 29;
UPDATE questions SET domain = 'Data acquisition and preparation' WHERE q_num = 30;
UPDATE questions SET domain = 'Data concepts and environments' WHERE q_num = 31;
UPDATE questions SET domain = 'Data analysis' WHERE q_num = 32;
UPDATE questions SET domain = 'Data analysis' WHERE q_num = 33;
UPDATE questions SET domain = 'Visualization and reporting' WHERE q_num = 34;
UPDATE questions SET domain = 'Data analysis' WHERE q_num = 35;
UPDATE questions SET domain = 'Visualization and reporting' WHERE q_num = 36;
UPDATE questions SET domain = 'Data governance' WHERE q_num = 37;
UPDATE questions SET domain = 'Data concepts and environments' WHERE q_num = 38;
UPDATE questions SET domain = 'Data analysis' WHERE q_num = 39;
UPDATE questions SET domain = 'Data governance' WHERE q_num = 40;
UPDATE questions SET domain = 'Data acquisition and preparation' WHERE q_num = 41;
UPDATE questions SET domain = 'Data analysis' WHERE q_num = 42;
UPDATE questions SET domain = 'Visualization and reporting' WHERE q_num = 43;
UPDATE questions SET domain = 'Data governance' WHERE q_num = 44;
UPDATE questions SET domain = 'Data analysis' WHERE q_num = 45;
UPDATE questions SET domain = 'Data concepts and environments' WHERE q_num = 46;
UPDATE questions SET domain = 'Data analysis' WHERE q_num = 47;
UPDATE questions SET domain = 'Visualization and reporting' WHERE q_num = 48;
UPDATE questions SET domain = 'Data governance' WHERE q_num = 49;
UPDATE questions SET domain = 'Data concepts and environments' WHERE q_num = 50;
UPDATE questions SET domain = 'Visualization and reporting' WHERE q_num = 51;
UPDATE questions SET domain = 'Data acquisition and preparation' WHERE q_num = 52;
UPDATE questions SET domain = 'Data concepts and environments' WHERE q_num = 53;
UPDATE questions SET domain = 'Data analysis' WHERE q_num = 54;
UPDATE questions SET domain = 'Data concepts and environments' WHERE q_num = 55;
UPDATE questions SET domain = 'Visualization and reporting' WHERE q_num = 56;
UPDATE questions SET domain = 'Data concepts and environments' WHERE q_num = 57;
UPDATE questions SET domain = 'Data concepts and environments' WHERE q_num = 58;
UPDATE questions SET domain = 'Data analysis' WHERE q_num = 59;
UPDATE questions SET domain = 'Data analysis' WHERE q_num = 60;
UPDATE questions SET domain = 'Data concepts and environments' WHERE q_num = 61;
UPDATE questions SET domain = 'Visualization and reporting' WHERE q_num = 62;
UPDATE questions SET domain = 'Data concepts and environments' WHERE q_num = 63;
UPDATE questions SET domain = 'Visualization and reporting' WHERE q_num = 64;
UPDATE questions SET domain = 'Data governance' WHERE q_num = 65;
UPDATE questions SET domain = 'Data governance' WHERE q_num = 66;
UPDATE questions SET domain = 'Data analysis' WHERE q_num = 67;
UPDATE questions SET domain = 'Data concepts and environments' WHERE q_num = 68;
UPDATE questions SET domain = 'Visualization and reporting' WHERE q_num = 69;
UPDATE questions SET domain = 'Data governance' WHERE q_num = 70;
UPDATE questions SET domain = 'Visualization and reporting' WHERE q_num = 71;
UPDATE questions SET domain = 'Data concepts and environments' WHERE q_num = 72;
UPDATE questions SET domain = 'Data governance' WHERE q_num = 73;
UPDATE questions SET domain = 'Data governance' WHERE q_num = 74;
UPDATE questions SET domain = 'Data acquisition and preparation' WHERE q_num = 75;
UPDATE questions SET domain = 'Data concepts and environments' WHERE q_num = 76;
UPDATE questions SET domain = 'Data acquisition and preparation' WHERE q_num = 77;
UPDATE questions SET domain = 'Data concepts and environments' WHERE q_num = 78;
UPDATE questions SET domain = 'Visualization and reporting' WHERE q_num = 79;
UPDATE questions SET domain = 'Data concepts and environments' WHERE q_num = 80;
UPDATE questions SET domain = 'Data analysis' WHERE q_num = 81;
UPDATE questions SET domain = 'Visualization and reporting' WHERE q_num = 82;
UPDATE questions SET domain = 'Visualization and reporting' WHERE q_num = 83;
UPDATE questions SET domain = 'Data analysis' WHERE q_num = 84;
UPDATE questions SET domain = 'Data governance' WHERE q_num = 85;
UPDATE questions SET domain = 'Data governance' WHERE q_num = 86;
UPDATE questions SET domain = 'Data governance' WHERE q_num = 87;
UPDATE questions SET domain = 'Visualization and reporting' WHERE q_num = 88;
UPDATE questions SET domain = 'Data analysis' WHERE q_num = 89;
UPDATE questions SET domain = 'Data acquisition and preparation' WHERE q_num = 90;
UPDATE questions SET domain = 'Data acquisition and preparation' WHERE q_num = 91;
UPDATE questions SET domain = 'Visualization and reporting' WHERE q_num = 92;
UPDATE questions SET domain = 'Data analysis' WHERE q_num = 93;
UPDATE questions SET domain = 'Data acquisition and preparation' WHERE q_num = 94;
UPDATE questions SET domain = 'Data concepts and environments' WHERE q_num = 95;
UPDATE questions SET domain = 'Data governance' WHERE q_num = 96;
UPDATE questions SET domain = 'Visualization and reporting' WHERE q_num = 97;
UPDATE questions SET domain = 'Visualization and reporting' WHERE q_num = 98;
UPDATE questions SET domain = 'Data analysis' WHERE q_num = 99;
UPDATE questions SET domain = 'Data concepts and environments' WHERE q_num = 100;
UPDATE questions SET domain = 'Data governance' WHERE q_num = 101;
UPDATE questions SET domain = 'Data analysis' WHERE q_num = 102;
UPDATE questions SET domain = 'Data analysis' WHERE q_num = 103;
UPDATE questions SET domain = 'Data governance' WHERE q_num = 104;
UPDATE questions SET domain = 'Data analysis' WHERE q_num = 105;
UPDATE questions SET domain = 'Data concepts and environments' WHERE q_num = 106;
UPDATE questions SET domain = 'Data governance' WHERE q_num = 107;
UPDATE questions SET domain = 'Data analysis' WHERE q_num = 108;
UPDATE questions SET domain = 'Data concepts and environments' WHERE q_num = 109;
UPDATE questions SET domain = 'Visualization and reporting' WHERE q_num = 110;

-- Questions below could not be auto-classified; defaulting to 'Data analysis'. Review manually.
UPDATE questions SET domain = 'Data analysis' WHERE q_num = 20;
UPDATE questions SET domain = 'Data analysis' WHERE q_num = 111;
UPDATE questions SET domain = 'Data analysis' WHERE q_num = 112;
UPDATE questions SET domain = 'Data analysis' WHERE q_num = 113;
UPDATE questions SET domain = 'Data analysis' WHERE q_num = 114;
UPDATE questions SET domain = 'Data analysis' WHERE q_num = 115;
UPDATE questions SET domain = 'Data analysis' WHERE q_num = 116;
UPDATE questions SET domain = 'Data analysis' WHERE q_num = 117;
UPDATE questions SET domain = 'Data analysis' WHERE q_num = 118;
UPDATE questions SET domain = 'Data analysis' WHERE q_num = 119;
UPDATE questions SET domain = 'Data analysis' WHERE q_num = 120;
UPDATE questions SET domain = 'Data analysis' WHERE q_num = 121;

-- Verify:
SELECT domain, COUNT(*) FROM questions GROUP BY domain;
